version: '3'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app_client
    container_name: app_client
    volumes:
      - ./.env:/root/.env
      - ./databases.json:/root/databases.json
      - ./logger.log:/root/logger.log
    depends_on:
      - mysql

  #MySQL
  mysql:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: golang
      MYSQL_PASSWORD: "golang"
      MYSQL_DATABASE: sekolah_beta
    networks:
      default:
        aliases:
          - db
#Volumes
volumes:
  mysql: